<a href="https://colab.research.google.com/github/amulyadav1517-jpg/Customer-Segmentation/blob/main/insurance_data_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv("insurance_data.csv")
df = pd.DataFrame(df)
df.head()

,Policy ID,Customer ID,Policy Type,Policy Start Date,Policy End Date,Premium Amount,Claim Status,Claim Amount,Claim Date,Customer Age,Customer Gender,Customer Income,Policy Duration (Months),Claim Frequency,Customer Location
0,P001,C001,Life,2017-12-27,2032-03-06,2305,Pending,0,2018-07-04,50,Male,115251,48,1,Chicago
1,P002,C002,Life,2022-10-25,2027-06-07,633,Closed,0,NaN,32,Female,94069,60,2,Chicago
2,P003,C003,Travel,2018-08-25,2025-07-23,1014,Open,859,2024-11-20,50,Female,120815,12,0,New York
3,P004,C004,Health,2024-03-14,2029-02-11,2832,Rejected,0,2019-10-01,67,Male,128140,48,1,Atlanta
4,P005,C005,Home,2021-12-19,2027-05-27,2870,Closed,0,NaN,57,Male,50347,36,0,Los Angeles

policy type

In [ ]:
df['Policy Type'].value_counts()

Policy Type
Life      175
Home      166
Health    154
Travel    153
Auto      152
Name: count, dtype: int64

customer location

In [ ]:
df['Customer Location'].value_counts()

Customer Location
Atlanta          91
San Francisco    89
Boston           84
Miami            81
Houston          80
Los Angeles      80
New York         79
Chicago          73
Seattle          72
Dallas           71
Name: count, dtype: int64

dataset info check

In [ ]:
print(df.info)

<bound method DataFrame.info of     Policy ID Customer ID Policy Type Policy Start Date Policy End Date  \
0        P001        C001        Life        2017-12-27      2032-03-06
1        P002        C002        Life        2022-10-25      2027-06-07
2        P003        C003      Travel        2018-08-25      2025-07-23
3        P004        C004      Health        2024-03-14      2029-02-11
4        P005        C005        Home        2021-12-19      2027-05-27
..        ...         ...         ...               ...             ...
795      P796        C796        Life        2021-08-24      2032-02-11
796      P797        C797        Auto        2015-07-25      2025-05-01
797      P798        C798      Travel        2024-03-04      2032-02-24
798      P799        C799        Home        2018-02-03      2030-04-16
799      P800        C800      Health        2018-03-30      2028-09-04

     Premium Amount Claim Status  Claim Amount  Claim Date  Customer Age  \
0              2305      Pending             0  2018-07-04            50
1               633       Closed             0         NaN            32
2              1014         Open           859  2024-11-20            50
3              2832     Rejected             0  2019-10-01            67
4              2870       Closed             0         NaN            57
..              ...          ...           ...         ...           ...
795             932         Open             0  2021-11-01            35
796            2157       Closed             0  2025-07-27            20
797             803     Rejected           611         NaN            20
798            3221         Open             0         NaN            53
799             691       Closed             0  2021-12-07            41

    Customer Gender  Customer Income  Policy Duration (Months)  \
0              Male           115251                        48
1            Female            94069                        60
2            Female           120815                        12
3              Male           128140                        48
4              Male            50347                        36
..              ...              ...                       ...
795            Male           112510                        72
796          Female           106960                        48
797            Male            83087                        12
798            Male            59568                        24
799            Male            77806                        60

     Claim Frequency Customer Location
0                  1           Chicago
1                  2           Chicago
2                  0          New York
3                  1           Atlanta
4                  0       Los Angeles
..               ...               ...
795                0            Boston
796                2             Miami
797                1     San Francisco
798                3             Miami
799                1           Chicago

[800 rows x 15 columns]>

summary statistics

In [ ]:
print(df.describe())

       Premium Amount  Claim Amount  Customer Age  Customer Income  \
count      800.000000    800.000000    800.000000       800.000000
mean      2718.827500   1329.938750     48.332500     91073.477500
std       1314.863836   1620.969184     18.609536     34946.744861
min        500.000000      0.000000     18.000000     30336.000000
25%       1589.250000      0.000000     32.000000     60362.250000
50%       2718.000000    347.500000     49.000000     92675.000000
75%       3856.250000   2648.250000     64.000000    120710.000000
max       4999.000000   4974.000000     80.000000    149974.000000

       Policy Duration (Months)  Claim Frequency
count                 800.00000       800.000000
mean                   41.44500         1.520000
std                    21.02295         1.109567
min                    12.00000         0.000000
25%                    24.00000         1.000000
50%                    36.00000         2.000000
75%                    60.00000         2.000000
max                    72.00000         3.000000

In [ ]:
print(df.isnull().sum())

Policy ID                     0
Customer ID                   0
Policy Type                   0
Policy Start Date             0
Policy End Date               0
Premium Amount                0
Claim Status                  0
Claim Amount                  0
Claim Date                  400
Customer Age                  0
Customer Gender               0
Customer Income               0
Policy Duration (Months)      0
Claim Frequency               0
Customer Location             0
dtype: int64

customer age

In [ ]:
df['Customer Age'].value_counts()

Customer Age
24    25
45    21
19    19
18    19
49    18
      ..
51     8
39     8
25     8
62     5
33     5
Name: count, Length: 63, dtype: int64

customer gender

In [ ]:
df['Customer Gender'].value_counts()

Customer Gender
Male      405
Female    395
Name: count, dtype: int64

policy duration (months)

In [ ]:
df['Policy Duration (Months)'].value_counts()

Policy Duration (Months)
24    149
12    143
72    143
48    129
60    120
36    116
Name: count, dtype: int64

customer income

In [ ]:
display(df['Customer Income'].describe())

count       800.000000
mean      91073.477500
std       34946.744861
min       30336.000000
25%       60362.250000
50%       92675.000000
75%      120710.000000
max      149974.000000
Name: Customer Income, dtype: float64

claim status

In [ ]:
display(df['Claim Status'].value_counts())

Claim Status
Rejected    205
Open        205
Pending     202
Closed      188
Name: count, dtype: int64

customer id

In [ ]:
display(df['Customer ID'].nunique())

800

In [ ]:
import pandas as pd

df = pd.read_csv("insurance_data.csv")
df = pd.DataFrame(df)